language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env.testing
  - mysql -e 'create database tracy_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan passport:keys
services:
  - mysql

script:
  - vendor/bin/phpunit

before_deploy:
  - git reset --hard

deploy:
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: develop

notifications:
  email: false
