language: php
php:
  - 7.2
before_script:
  - cp .env.travis .env.testing
  - mysql -e 'create database tracy_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan passport:keys
services:
  - mysql
script:
  - vendor/bin/phpunit
before_deploy:
  - openssl aes-256-cbc -K $encrypted_40647c782b71_key -iv $encrypted_40647c782b71_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "HostName wernerd.info\n\tStrictHostKeyChecking no\n\t"User deploy >> ~/.ssh/config
deploy:
  skip_cleanup: true
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: develop
notifications:
  email: false
